# Generated by Django 4.1.5 on 2023-02-28 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator('5'), django.core.validators.MaxLengthValidator('10')]),
        ),
    ]
