# Generated by Django 4.1.5 on 2023-02-28 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
