# Generated by Django 4.1.5 on 2023-02-28 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5)]),
        ),
    ]
